Repository MARKETProtocol/MARKET.js, pull requests merged in 2018-06, with the labels that each got.

#19 Initial commit for Order
  .travis.yml
  package-lock.json
  package.json
  rollup.config.ts
  src/Market.ts
  src/SchemaValidator.ts
  src/assert.ts
  src/constants.ts
  src/index.ts
  src/lib/Order.ts
  src/lib/Util.ts
  src/lib/Utils.ts
  src/schemas/OrderSchema.ts
  src/schemas/index.ts
  src/types/CollateralToken.ts
  src/types/ERC20.ts
  src/types/MarketCollateralPool.ts
  src/types/MarketCollateralPoolFactory.ts
  src/types/MarketCollateralPoolFactoryInterface.ts
  src/types/MarketContract.ts
  src/types/MarketContractFactoryOraclize.ts
  src/types/MarketContractOraclize.ts
  src/types/MarketContractRegistry.ts
  src/types/MarketContractRegistryInterface.ts
  src/types/MarketToken.ts
  src/types/OraclizeQueryTest.ts
  src/types/Order.ts
  src/types/OrderLib.ts
  src/types/typechain-runtime.ts
  templates/README.md
  test/Collateral.test.ts
  test/Contract.test.ts
  test/Market.test.ts
  test/Order.test.ts
  test/Settlement.test.ts
  test/SimEx.test.ts
  test/Util.test.ts
  test/Utils.test.ts
  tsconfig.json
  types/README.md
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#27 Feature/unallocated token balance #26
  src/lib/Collateral.ts
  test/Collateral.test.ts
Labels: Status: Completed

#30 Access the collateral pool contract address
  src/index.ts
  src/lib/Contract.ts
  test/Contract.test.ts
Labels: Status: Review Needed

#42 Expose all available methods in `Market.ts`.
  src/Market.ts
  src/lib/Collateral.ts
  src/lib/Contract.ts
  src/lib/Deployment.ts
  src/lib/Order.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#44 [WIP] add new ExpirationWatcher class fixes #37
  package-lock.json
  package.json
  src/Market.ts
  src/constants.ts
  src/lib/Order.ts
  src/lib/Utils.ts
  src/order_watcher/ExpirationWatcher.ts
  src/types/MarketError.ts
  src/types/Order.ts
  src/utilities/Empty.ts
  test/Deployment.test.ts
  test/ExpirationWatcher.test.ts
  test/Order.test.ts
Labels: Priority: High, Status: Review Needed

#48 Update the makefile to use truffle@4.1.11 and update the readme.
  Makefile
  README.md
Labels: Type: Bug

#50 implement getQtyFilledOrCancelledFromOrderAsync
  src/Market.ts
  src/lib/Order.ts
  test/Order.test.ts
Labels: Priority: Medium, Status: Revision Needed, Type: Enhancement

#52 Update MARKET pkgs and filter deployment events
  package-lock.json
  package.json
  src/lib/Deployment.ts
Labels: Priority: Medium

#54 add tests for Assert and Utils
  test/Assert.test.ts
  test/Utils.test.ts
Labels: Priority: Low
