Repository MARKETProtocol/MARKET.js, pull requests merged in 2018-05, with the labels that each got.

#15 Feature/dev environment #5
  .gitignore
  Makefile
  README.md
  contracts/Migrations.sol
  migrations/1_initial_migration.js
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
  truffle-config.js
  truffle.js
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#11 Update module project structure
  .gitignore
  Makefile
  README.md
  contracts/Migrations.sol
  migrations/1_initial_migration.js
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
  src/lib/Collateral.ts
  src/lib/Contract.ts
  src/lib/Order.ts
  src/lib/Settlement.ts
  src/lib/SimEx.ts
  src/lib/Util.ts
  src/marketjs.ts
  templates/README.md
  test/Collateral.test.ts
  test/Contract.test.ts
  test/Order.test.ts
  test/Settlement.test.ts
  test/SimEx.test.ts
  test/Util.test.ts
  test/marketjs.test.ts
  truffle-config.js
  truffle.js
  types/README.md
Labels: Status: Review Needed, Type: Enhancement

#16 Initial commit for configuring web3
  .DS_Store
  .github/CONTRIBUTING.md
  .travis.yml
  package-lock.json
  package.json
  rollup.config.ts
  src/Market.ts
  src/index.ts
  src/marketjs.ts
  test/Collateral.test.ts
  test/Contract.test.ts
  test/Market.test.ts
  test/Order.test.ts
  test/Settlement.test.ts
  test/SimEx.test.ts
  test/Util.test.ts
  tsconfig.json
  tslint.json
Labels: Priority: High, Status: Review Needed, Type: Enhancement
